name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        if: ${{ github.ref != 'refs/heads/main' }}
        with:
          push: true
          tags: omegavesko/serbian-bank-ynab-sync-agent:${{ github.sha }}

      - name: Build and push Docker image (tags latest)
        uses: docker/build-push-action@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          push: true
          tags: omegavesko/serbian-bank-ynab-sync-agent:${{ github.sha }},omegavesko/serbian-bank-ynab-sync-agent:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Kubernetes context
        uses: azure/k8s-set-context@v1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v1.4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          namespace: "serbian-bank-ynab-sync-agent"
          manifests: |
            .infra/kubernetes/deployment.yaml
          images: omegavesko/serbian-bank-ynab-sync-agent:${{ github.sha }}
